### ISSUE TITLE
Adicionar migrations ao processo de criação de tabelas no banco de dados

### ISSUE THREAD

**Issue by tchaguitos** [tchaguitos/glicobuddy#24]
### tasks

- [ ] Instalar Alembic
- [ ] Criar `env.py`
- [ ] Testar fluxo de criação de migrations
- [ ] Testar `upgrade` e `downgrade`

### referências 
- https://alembic.sqlalchemy.org/en/latest/front.html#installation
