### ISSUE TITLE
Adicionar autenticação bearer em endpoints

### ISSUE THREAD

**Issue by tchaguitos** [tchaguitos/glicobuddy#27]
### referências: 

1. https://fastapi.tiangolo.com/tutorial/security/
2. https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/

### tasks principais
- [x] Proteger endpoints de acesso não autenticado
- [x] Consultar id de usuários logado (para vincular às glicemias e realizar operações como atualizar cadastro, alterar e-mail, etc)
- [x] Alterar `Encriptador` e `GeradorDeToken` para utilizarem o `CryptContext` do `passlib`
