### ISSUE TITLE
Vincular glicemias ao usuário logado

### ISSUE THREAD

**Issue by tchaguitos** [tchaguitos/glicobuddy#31]
Atualmente a autenticação e identificação do usuário já está sendo desenvolvida na branch `feat/add-bearer-auth`, todavia, é necessário ajustar a camada de persistência pra salvar essas informações corretamente

## tasks principais
- [ ] Adiciona campo foreign key na tabela de glicemias
- [ ] Alterar o mapeamento da classe para refletir a mudança
- [ ] Alterar e escrever testes
- [ ] Consultar glicemias por usuário

### tasks secundárias
- [ ] Bloquear acesso de usuários em glicemias que não estão vinculadas ao seu id
